site_name: Azkaban
site_url: http://docs.home/
site_description: Resources for my Home Lab
site_author: Thomas Kortyka
copyright: Copyright &copy; 2022 Thomas Kortyka

repo_url: https://github.com/ToxicToast/homelab
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Services:
      - Azkaban: services/azkaban.md

theme:
  name: 'material'
  palette:
    primary: black
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tooltips
    - toc.follow
  language: en
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path: docs
  - def_list
  - pymdownx.tasklist:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/toxictoast
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/toxictoastsc2